# Generated by Django 5.1 on 2024-08-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('recipient', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('message', models.JSONField()),
            ],
        ),
    ]
