# Generated by Django 5.1 on 2024-08-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='logs',
        ),
    ]
